### ISSUE TITLE
NetworkSummary and NetworkStructure error

### ISSUE THREAD

**Issue by lfelipecl** [stewid/EpiContactTrace#3]
I was just following the example of your paper and got the following error after run "NetworkSummary" and "NetworkStructure":
`Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘NetworkStructure’ for signature ‘"list"’`

I was looking for the cause on the internet and found that it usually happens when there is a conflict between two functions in different packages, but the thing is I didn't load any package further than default ones and EpiContactTrace.

The whole code: 
`>install.packages("EpiContactTrace")
>library(EpiContactTrace)
>data("transfers")
>root <- c(2645, 2838)
>tEnd <- "2005-10-31"
>days <- 90
>contactTrace <- Trace(transfers,root,tEnd,days)
>NetworkSummary(contactTrace)
>NetworkStructure(contactTrace)`

**Comment by stewid** [comment]
Thanks for reporting the issue. I can reproduce it and I'm working on fixing the bug.

**Comment by stewid** [comment]
A new version 0.15.0 that fixes the issue has been submitted to CRAN.
