### ISSUE TITLE
https://github.com/stewid/EpiContactTrace

### ISSUE THREAD

**Issue by vzavaletag** [stewid/EpiContactTrace#4]

**Comment by vzavaletag** [comment]
ic.2 <- IngoingContactChain(movements = transfers,
+                             root = 2645,
+                             tEnd = "2005-10-31",
+                             days = 91)

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘IngoingContactChain’ for signature ‘"missing"’

**Comment by vzavaletag** [comment]
No ejecuta y sale error

**Comment by stewid** [comment]
Thanks for reporting the issue. I've updated the examples and they now work. I will submit a new version to CRAN.

**Comment by stewid** [comment]
A new version is now on CRAN.
